# This file was generated by study_builder.views_builder.py

from django.http import *
from django.contrib.auth.decorators import login_required
from django.template import Template, Context, RequestContext


@login_required
def aiming_test_study_consent(request):
    template_file = open("/Users/kante/Documents/work/tangra/Tangra/portal/user_studies/aiming_test_study/stages/consent/template.html", "r")
    template = Template("".join(template_file.readlines()))
    context = RequestContext(request)
    return HttpResponse(template.render(context))


@login_required
def aiming_test_study_instructions(request):
    template_file = open("/Users/kante/Documents/work/tangra/Tangra/portal/user_studies/aiming_test_study/stages/instructions/template.html", "r")
    template = Template("".join(template_file.readlines()))
    context = RequestContext(request)
    return HttpResponse(template.render(context))


@login_required
def aiming_test_study_aiming_task(request):
    template_file = open("/Users/kante/Documents/work/tangra/Tangra/portal/user_studies/aiming_test_study/stages/aiming_task/template.html", "r")
    template = Template("".join(template_file.readlines()))
    context = RequestContext(request)
    return HttpResponse(template.render(context))


@login_required
def aiming_test_study_continuation(request):
    template_file = open("/Users/kante/Documents/work/tangra/Tangra/portal/user_studies/aiming_test_study/stages/continuation/template.html", "r")
    template = Template("".join(template_file.readlines()))
    context = RequestContext(request)
    return HttpResponse(template.render(context))


@login_required
def another_study_welcome_page(request):
    template_file = open("/Users/kante/Documents/work/tangra/Tangra/portal/user_studies/another_study/stages/welcome_page/template.html", "r")
    template = Template("".join(template_file.readlines()))
    context = RequestContext(request)
    return HttpResponse(template.render(context))


@login_required
def another_study_simple_task(request):
    template_file = open("/Users/kante/Documents/work/tangra/Tangra/portal/user_studies/another_study/stages/simple_task/template.html", "r")
    template = Template("".join(template_file.readlines()))
    context = RequestContext(request)
    return HttpResponse(template.render(context))


@login_required
def another_study_bye_page(request):
    template_file = open("/Users/kante/Documents/work/tangra/Tangra/portal/user_studies/another_study/stages/bye_page/template.html", "r")
    template = Template("".join(template_file.readlines()))
    context = RequestContext(request)
    return HttpResponse(template.render(context))


@login_required
def example_study_welcome_page(request):
    template_file = open("/Users/kante/Documents/work/tangra/Tangra/portal/user_studies/example_study/stages/welcome_page/template.html", "r")
    template = Template("".join(template_file.readlines()))
    context = RequestContext(request)
    return HttpResponse(template.render(context))


@login_required
def example_study_simple_task(request):
    template_file = open("/Users/kante/Documents/work/tangra/Tangra/portal/user_studies/example_study/stages/simple_task/template.html", "r")
    template = Template("".join(template_file.readlines()))
    context = RequestContext(request)
    return HttpResponse(template.render(context))


@login_required
def example_study_bye_page(request):
    template_file = open("/Users/kante/Documents/work/tangra/Tangra/portal/user_studies/example_study/stages/bye_page/template.html", "r")
    template = Template("".join(template_file.readlines()))
    context = RequestContext(request)
    return HttpResponse(template.render(context))


@login_required
def shipley_vocabulary_test_welcome_page(request):
    template_file = open("/Users/kante/Documents/work/tangra/Tangra/portal/user_studies/shipley_vocabulary_test/stages/welcome_page/template.html", "r")
    template = Template("".join(template_file.readlines()))
    context = RequestContext(request)
    return HttpResponse(template.render(context))


@login_required
def shipley_vocabulary_test_test(request):
    template_file = open("/Users/kante/Documents/work/tangra/Tangra/portal/user_studies/shipley_vocabulary_test/stages/test/template.html", "r")
    template = Template("".join(template_file.readlines()))
    context = RequestContext(request)
    return HttpResponse(template.render(context))


@login_required
def simple_word_game_study_boggle(request):
    template_file = open("/Users/kante/Documents/work/tangra/Tangra/portal/user_studies/simple_word_game_study/stages/boggle/template.html", "r")
    template = Template("".join(template_file.readlines()))
    context = RequestContext(request)
    return HttpResponse(template.render(context))


@login_required
def simple_word_game_study_shipley(request):
    template_file = open("/Users/kante/Documents/work/tangra/Tangra/portal/user_studies/simple_word_game_study/stages/shipley/template.html", "r")
    template = Template("".join(template_file.readlines()))
    context = RequestContext(request)
    return HttpResponse(template.render(context))


@login_required
def simple_word_game_study_consent(request):
    template_file = open("/Users/kante/Documents/work/tangra/Tangra/portal/user_studies/simple_word_game_study/stages/consent/template.html", "r")
    template = Template("".join(template_file.readlines()))
    context = RequestContext(request)
    return HttpResponse(template.render(context))

